name: Release Workflow

on:
  workflow_run:
    workflows: ["CI (Continuous Integration)"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Git Config
      run: |
        git config --global user.email "zerkxubas@gmail.com"
        git config --global user.name "Subash Sharma"
        git config --list  # Add this line for debugging

    # - name: Fetch tags
    #   run: git fetch --tags

    - name: Bump version and create tag
      id: tag_version
      run: |
        git fetch --tags
    
         # Get the latest tag
        latest_tag=$(git tag -l --sort=-v:refname | head -n 1)
        if [ -z "$latest_tag" ]; then
          new_version="v1.0.0"
        else
          # Strip 'v' prefix if exists
          current_version=${latest_tag#v}
          IFS='.' read -r major minor patch <<< "$current_version"
          new_version="v$major.$minor.$((patch + 1))"
        fi
    
        echo "New version: $new_version"
        echo "new_version=$new_version" >> $GITHUB_ENV 
    
        git tag $new_version
        git push origin $new_version

    - name: Wait for tag propagation
      run: sleep 10s

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        body: "Automated release ${{ github.ref_name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}